import React from 'react';
import Card from '@mui/material/Card';
import Typography from '@mui/material/Typography';
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import LinearProgress from '@mui/material/LinearProgress';
import { dateFormat, IdPrefixFormat } from '@bridgeup/common/formatter';
import { Chip } from '@mui/material';
import { RatingChart } from './RatingChart';

interface BridgeUpScoreProps {
  dealId: number;
  companyId: number;
  bupScore: any;
}

const BridgeUpScore: React.FC<BridgeUpScoreProps> = ({
  dealId,
  companyId,
  bupScore,
}) => {
  const Parameters = [
    {
      title: 'Financials',
      value: bupScore?.financials,
    },
    {
      title: 'Business Growth',
      value: bupScore?.businessGrowth,
    },
    {
      title: 'Capital Efficiency',
      value: bupScore?.capitalEfficiency,
    },
    {
      title: 'Customer Value',
      value: bupScore?.customerValue,
    },
    {
      title: 'Compliance',
      value: bupScore?.compliance,
    },
  ];

  const renderParameters = (
    parameter: { title: any; value: any },
    index: number
  ) => {
    const renderTitle = (title: string) => {
      return <Typography variant="body2">{title}</Typography>;
    };

    const renderProgressBar = (value: number) => {
      return (
        <Box className="grow">
          <LinearProgress
            variant="determinate"
            value={value * 20}
            className={`${
              value < 2.5
                ? 'bup-com-progress-bar-red'
                : value > 3.5
                ? 'bup-com-progress-bar-green'
                : 'bup-com-progress-bar-orange'
            }`}
          />
        </Box>
      );
    };

    const renderValue = (value: number) => {
      const color: 'success' | 'error' | 'warning' =
        value < 2.5 ? 'error' : value > 3.5 ? 'success' : 'warning';
      return (
        <Chip
          label={value.toFixed(1)}
          color={color}
          variant="outlined"
          sx={{ fontWeight: 700 }}
        />
      );
    };

    return (
      <Grid
        container
        item
        xs={12}
        alignItems={'center'}
        columnSpacing={6}
        mt={2}
        key={index}
      >
        <Grid item xs={3}>
          {renderTitle(parameter?.title || '')}
        </Grid>
        <Grid item xs>
          {renderProgressBar(parameter?.value || 0)}
        </Grid>
        <Grid item xs={'auto'}>
          {renderValue(parameter?.value || 0)}
        </Grid>
      </Grid>
    );
  };

  return (
    <Card className="basic-card">
      RatingChart
      <Typography variant="body1" mb={3.5}>
        BridgeUp score is a rating between 1 to 10 generated by the scoring
        engine taking into account a company’s subscription, banking and
        accounting data. It Indicates the creditworthiness of the company to
        receive the payout..
      </Typography>
      <Grid container spacing={2}>
        <Grid container item xs={12} md={5}>
          <Grid
            item
            xs={12}
            display={'flex'}
            flexDirection={'column'}
            className="text-center"
            justifyContent={'flex-end'}
            alignItems={'center'}
          >
            <Box
              mb={3}
              width={220}
              display={'block'}
              sx={{ position: 'relative' }}
            >
              {bupScore?.rating && <RatingChart rating={bupScore.rating} />}
              <Box sx={{ position: 'absolute', width: '100%', bottom: 0 }}>
                <Typography
                  variant="body1"
                  gutterBottom
                  component="span"
                  fontWeight={700}
                  fontSize={48}
                >
                  {bupScore?.rating || 0}/
                </Typography>
                <Typography
                  variant="body1"
                  gutterBottom
                  component="span"
                  fontWeight={700}
                  fontSize={24}
                  className="text-color-3"
                >
                  10
                </Typography>
              </Box>
            </Box>

            <Box mb={3}>
              <Typography
                variant="h6"
                gutterBottom
                component="div"
                fontWeight={700}
              >
                {IdPrefixFormat(companyId, 'COMP')}
              </Typography>
            </Box>
            <Box>
              <Typography variant="body2" gutterBottom className="text-color-3">
                Company Last Evaluated On:
              </Typography>
              <Typography variant="body2" gutterBottom fontWeight={700}>
                {dateFormat(bupScore.updatedAt)}
              </Typography>
            </Box>
          </Grid>
        </Grid>
        <Grid container item xs={12} md={7}>
          <Grid item xs={12}>
            <Typography
              variant="h6"
              gutterBottom
              component="div"
              fontWeight={700}
            >
              Parameter
            </Typography>
          </Grid>
          <Grid container item xs={12}>
            {Parameters.map((parameter, index) => {
              return renderParameters(parameter, index);
            })}
          </Grid>
        </Grid>
      </Grid>
    </Card>
  );
};

export default BridgeUpScore;
