[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; form-action 'self'; script-src 'self' 'unsafe-eval' www.google-analytics.com www.googletagmanager.com *.mouseflow.com cdn.segment.com; connect-src 'self' *.devbridgeup.com *.bridgeup.com bridgeup-dev-objects.s3.ap-southeast-1.amazonaws.com bridgeup-prod-objects.s3.ap-south-1.amazonaws.com s3.ap-southeast-1.amazonaws.com s3.ap-south-1.amazonaws.com bridgeup-stage-objects.s3.amazonaws.com s3.us-east-1.amazonaws.com www.google-analytics.com www.googletagmanager.com *.mouseflow.com cdn.segment.com; img-src 'self' data: cloudfront.net *.cloudfront.net cdn.bridgeup.com bridgeup-dev-objects.s3.ap-southeast-1.amazonaws.com bridgeup-prod-objects.s3.ap-south-1.amazonaws.com bridgeup-stage-objects.s3.ap-south-1.amazonaws.com www.google-analytics.com www.googletagmanager.com cdn.segment.com; base-uri 'self';media-src cdn.bridgeup.com; script-src-elem 'self' 'unsafe-inline' googletagmanager.com *.googletagmanager.com google-analytics.com *.google-analytics.com cdn.segment.com"
